### ISSUE TITLE
EPIC work mate

### ISSUE THREAD

**Issue by Caffiene0Addict0420** [lorpus/pyhq#1]
Would it be ok if you could give me an example in python of how to use these classes and functions to create an account, validate it, input a referral code and join a game? or create a readme with this in?

many thanks
caffiene addict

**Comment by lorpus** [comment]
use these functions in order downwards to create an account: https://github.com/lorpus/pyhq/blob/master/pyhq.py#L280
check my comment on #2 about connecting
