### ISSUE TITLE
How to join a game using api?

### ISSUE THREAD

**Issue by vocabexpresshaxer** [lorpus/pyhq#2]
Thanks mate for making this. Basically, @lorpus how do you join a game with an instance of the HQ client class? Basically, this is what ive got so far

`import` random
ver = verify(input("Phone Number: "))
u = "False"
while u == "False":
    uname = str(random.randint(1000, 100000))
    u = str(username_available(uname))
print(uname)
if str(submit_code(ver, input("Code: "))) == "True":
    auth = create_user(uname, ver, "referal code", "UK")['authToken']
    print(auth)
    test = HQClient(auth)
    if test.make_it_rain() != True:print("Could not provide extra life to account")
    else:print("Wahoo! Extra life given to the account!")
    #print(test.generate_extra_life(1))
    
else:
    print("Invalid Code")

**Comment by lorpus** [comment]
you have to handle the websocket stuff yourself. you can get the active socket url if a game is active with client.socket_url() and once you connect then send the subscribe message with client.generate_subscribe(). afterwards you can send an answer over the socket with client.generate_answer(question_id, answer_id). question_id and answer_id are sent to the client once a question is asked.

**Comment by vocabexpresshaxer** [comment]
Thanks sooo much 😊

**Comment by vocabexpresshaxer** [comment]
So if I use test = HHClient(and put Auth token here)

Can I just do test.generate_subscribe() to join a game once it is active or
do I need to send the default headers and the result from the function to
the socket URL?

**Comment by lorpus** [comment]
you have to connect to the websocket with another module and send the header "Authorization: Bearer <auth here>" and then send the generate_subscribe string over the websocket. this module doesn't handle the websocket, just ways to create strings to send over the websocket you create yourself.

**Comment by vocabexpresshaxer** [comment]
👍

**Comment by vocabexpresshaxer** [comment]
Sorry lorpus, one more final question- what is the URL to send the
subscribe msg to? Many thanks

Caffeine Addict

**Comment by lorpus** [comment]
over the websocket returned by client.socket_url() (None if no game is active)
