### ISSUE TITLE
How to check if user is in or out?

### ISSUE THREAD

**Issue by ZachC16** [lorpus/pyhq#6]
How do I check whether my user is still in the game or out when playing over websocket? How do I know if I got a question right or wrong and use a life if wrong?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lorpus** [comment]
a json object will be sent over the socket with the key "type" defined as "questionSummary" and if you got it right then the appropriately-named key "youGotItRight" will be defined as true.

to use a life, call the generate_extra_life method (make sure to pass question_id) and then send the result of that method over the socket

**Comment by vocabexpresshaxer** [comment]
Take a look at this JSON Dump, it has all the info you need really
https://pastebin.com/ufMKWcNB

**Comment by ZachC16** [comment]
@vocabexpresshaxer Do I replace xxxxxxx with my auth token or "Bearer "+ my auth token?

**Comment by vocabexpresshaxer** [comment]
Just your Auth token
