### ISSUE TITLE
API needs to be updated (when creating a user)

### ISSUE THREAD

**Issue by vocabexpresshaxer** [lorpus/pyhq#7]
It was working 100%, but now after the verify is called, always an error occurs (the number is correct, not a single number works). I believe HQ have updated the API so this code needs revising (if you provide the data dumps as a JSON file I'll happily do this for you and submit a pull request)

**Comment by ZachC16** [comment]
Get rid of the exception handler and see exactly what the error is. Post it here if you get a chance. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lorpus** [comment]
i believe i need to add some headers, i'll be updating it within the hour :)

**Comment by vocabexpresshaxer** [comment]
Wow- thanks 👍
